name: Publish

on:
  push:
    tags:
      - 'v*'
      
  workflow_dispatch:

jobs:
  publish:
    name: Publish module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
            fetch-depth: 0
      
      - name: Get latest tag
        id: latestTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      
      - name: Publish GitHub release
        id: githubRelease
        uses: maxkomarychev/oction-create-release@v0.6.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: ${{ steps.latestTag.tag }}
          draft: true

      - name: Publish to PSGallery
        if: steps.githubRelease.conclusion == 'success'
        shell: pwsh
        env:
          PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
        run: Publish-Module -Name ./CITest/CITest.psd1 -NuGetApiKey $env:PSGALLERY_TOKEN -AllowPrerelease -Verbose
