name: Publish

on:
  workflow_run:
    workflows: ['Build']
    branches: [main]
    types:
      - completed
    
  workflow_dispatch:

jobs:
  publish:
    name: Publish module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Test git
        run: git tag
      
      - name: Get latest tag
        id: latestTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      
      - name: Publish GitHub release
        id: githubRelease
        uses: Roang-zero1/github-create-release-action@v2.1.0
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          created_tag: "v${{ steps.latestTag.tag }}"
          create_draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PSGallery
        if: steps.githubRelease.conclusion == 'success'
        shell: pwsh
        env:
          PSGALLERY_TOKEN: ${{ secrets.PSGALLERY_TOKEN }}
        run: Publish-Module -Name ./CITest/CITest.psd1 -NuGetApiKey $env:PSGALLERY_TOKEN -AllowPrerelease -Verbose
