name: Publish

on:
  workflow_run:
    workflows: ['Build']
    branches: [main]
    types:
      - completed
      
  workflow_dispatch:

jobs:
  publish:
    name: Publish module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
            fetch-depth: 0
            
      - name: Create variables for module cacher
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v3.5
        with:
          modules-to-cache: SimplySql
          shell: pwsh

      - name: Run module cacher action
        id: cacher
        uses: actions/cache@v2
        with:
          key: ${{ steps.psmodulecache.outputs.keygen }}
          path: |
            ${{ steps.psmodulecache.outputs.modulepath }}
            
      - name: Install PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        uses: potatoqualitee/psmodulecache@v3.5

      - name: Import SimplySql
        shell: pwsh
        run: Import-Module SimplySql -ErrorAction Stop
      
      - name: Get latest tag
        id: latestTag
        uses: WyriHaximus/github-action-get-previous-tag@v1
      
      - name: Publish GitHub release
        id: githubRelease
        uses: Roang-zero1/github-create-release-action@v2.1.0
        with:
          version_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          prerelease_regex: ^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
          created_tag: ${{ steps.latestTag.outputs.tag }}
          create_draft: true
          update_existing: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to PSGallery
        if: steps.githubRelease.conclusion == 'success'
        uses: pcgeek86/publish-powershell-module-action@v20
        with:
          modulePath: ./CITest/
          NuGetApiKey: ${{ secrets.PSGALLERY_TOKEN }}
