name: Test module
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**/README.md'
      - '.github/**'

jobs:
  test:
    name: Test module
    runs-on: windows-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Create variables for module cacher
        id: psmodulecache
        uses: potatoqualitee/psmodulecache@v3.5
        with:
          modules-to-cache: Pester, PSScriptAnalyzer, InvokeBuild, SimplySql
          shell: pwsh
          
      - name: Run module cacher action
        id: cacher
        uses: actions/cache@v2
        with:
          key: ${{ steps.psmodulecache.outputs.keygen }}
          path: |
            ${{ steps.psmodulecache.outputs.modulepath }}
            
      - name: Install PowerShell modules
        if: steps.cacher.outputs.cache-hit != 'true'
        uses: potatoqualitee/psmodulecache@v3.5
        
      - name: Import InvokeBuild
        run: Import-Module InvokeBuild -ErrorAction Stop

      - name: Analyze code with PSScriptAnalyzer
        run: Invoke-Build -Task Analyze

      - name: Upload Analyzer Results as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: AnalyzerResults
          path: .\build\AnalyzerResults.xml

      - name: Test code with Pester tests
        run: Invoke-Build -Task Test

      - name: Upload Pester Results as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: PesterResults
          path: .\build\PesterResults.xml

      - name: Upload Code Coverage as artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: CodeCoverage
          path: .\build\CodeCoverage.xml
